// Auth
export const USER_LOGGED_IN = "USER_LOGGED_IN"
export const USER_LOGGED_OUT = "USER_LOGGED_OUT"

// User
export const USER_FETCHED = "USER_FETCHED"
export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST"
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE"

// Locale
export const LOCALE_SET = "LOCALE_SET"
