// Auth
export const USER_LOGGED_IN = "USER_LOGGED_IN"
export const USER_LOGGED_OUT = "USER_LOGGED_OUT"

// User
export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST"
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE"
export const FETCH_CURRENT_USER_REQUEST = "FETCH_CURRENT_USER_REQUEST"
export const FETCH_CURRENT_USER_SUCCESS = "FETCH_CURRENT_USER_SUCCESS"
export const FETCH_CURRENT_USER_FAILURE = "FETCH_CURRENT_USER_FAILURE"

// Locale
export const LOCALE_SET = "LOCALE_SET"
